[package]
name = "dotavious"
version = "0.1.0"
authors = ["seancarroll"]
description = "A library for generating Graphviz DOT language files for graphs."
edition = "2018"
readme = "README.md"
repository = "https://github.com/doctavious/dotavious"