name: Publish

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Publish
        run: |
          cargo login ${{ secrets.CARGO_API_KEY }}
          cargo publish